Change compile target to ES2018
Fix a test that fails in CI.

  test/group.test.ts:69:22 - error TS2339: Property 'groups' does not exist on type 'RegExpExecArray'.

  69       expect(matches.groups).toEqual({